[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
hello_world = "6ZFL2Q7eaqL7LCvjKEALjYHcCeN8hTFBfcVtJfyfef6k"

[programs.devnet]
hello_world = "6ZFL2Q7eaqL7LCvjKEALjYHcCeN8hTFBfcVtJfyfef6k"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/home/dan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
